name: hacettepe_precipitation
channels:
  - defaults
dependencies:
  - python=3.6.9
  - matplotlib=3.3.4
  - numpy=1.19.2
  - pandas=1.1.3
  - scipy=1.5.2
  - seaborn=0.11.0
  - notebook=6.2.0
  - scikit-learn=0.24.1
